#!/usr/bin/osascript

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Zzz
# @raycast.mode silent

# Optional parameters:
# @raycast.icon 💤

# Documentation:
# @raycast.author Marc-Antoine Ferland
# @raycast.authorURL https://github.com/maferland

do shell script "pmset sleepnow"
